name: "customer-engineering"
version: '3'
services:
  nestjs:
    restart: always
    build:
      context: ../
      dockerfile: ./devops/Dockerfile
    ports:
      - "4444:4444"
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: customer_engineering  #${DB_NAME}
      MYSQL_USER: admin #${DB_USER}
      MYSQL_PASSWORD: password #${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: