name: "customer-engineering"
version: '3'
services:
  nestjs:
    restart: always
    build:
      context: ../
      dockerfile: ./devops/Dockerfile
    ports:
      - "4444:4444"
      - "9229:9229"
    volumes:
      - ../:/var/www/html

  mysql:
    image: mysql:8.0
    platform: linux/amd64
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: customer_engineering  #${DB_NAME}
      MYSQL_USER: admin #${DB_USER}
      MYSQL_PASSWORD: password #${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mysql_data:
